### ISSUE TITLE
Erreur lors de l'ouverture le tutoriel

### ISSUE THREAD

**Issue by eduardoafontana** [StevenCostiou/PharoVariableBreakpointExperiment#1]
Je ne sais pas si c'est critique. 

![image](https://user-images.githubusercontent.com/6172732/122429904-22597f00-cf61-11eb-9302-f004518f0c05.png)

**Comment by StevenCostiou** [comment]
Peux tu reproduire et me montrer la stack dans le debugger ? 
Je voudrais voir plus de méthodes pour voir d'où ça vient.
Je n'arrive pas à reproduire ce problème.

**Comment by eduardoafontana** [comment]
Cette vidéo montre l'erreur qui se produit lors de l'ouverture de la task, ainsi que la stack dans le debugger. Notez qu'il crée un fichier .DS_Store dans le dossier swarm. Dans la première version de l'image n'a pas créé.

https://www.youtube.com/watch?v=F_0NfPLEuYg

**Comment by eduardoafontana** [comment]
Ok, résolu dans la version de l'image sortie le 22 juin, version 5.
