### ISSUE TITLE
Pass ne permet pas de démarrer une nouvelle tâche

### ISSUE THREAD

**Issue by eduardoafontana** [StevenCostiou/PharoVariableBreakpointExperiment#4]
Si je clique sur Pass dans la fenêtre Finish Task, lorsque j'essaie de démarrer une autre tâche, cela indique que je travaille toujours sur la précédente. Je ne pense pas être critique.

![image](https://user-images.githubusercontent.com/6172732/122432221-21c1e800-cf63-11eb-8854-9b095eb5d5f5.png)

**Comment by StevenCostiou** [comment]
Fixed

**Comment by eduardoafontana** [comment]
Tested. Ok.
