### ISSUE TITLE
Tâche warm-up ne montre pas comment le test doit être effectué

### ISSUE THREAD

**Issue by eduardoafontana** [StevenCostiou/PharoVariableBreakpointExperiment#5]
Dans la tâche warm-up, il ne montre pas comment le test doit être effectué. Si le développeur n'a jamais fait de test sur Pharo, il peut avoir des doutes. Il peut être intéressant de le compléter avec le code d'exécution du test: VBTAlignmentTest new testFailingAlignment .

**Comment by eduardoafontana** [comment]
Vérifié à l'image du 22 juin et la situation continue. Il n'y a aucune information sur la façon d'exécuter le test.

**Comment by StevenCostiou** [comment]
J'ai mis un screenshot dans la warm-up 1, je suppose d'une part que cela sera suffisant (pas de répétition dans les autres tâches) et d'autre part que les participants seront familiers avec Pharo.

**Comment by eduardoafontana** [comment]
Tested, ok.
