### ISSUE TITLE
La description du test en warm-up 2 n'est pas claire

### ISSUE THREAD

**Issue by eduardoafontana** [StevenCostiou/PharoVariableBreakpointExperiment#7]
Dans la tâche de warm-up 2, la partie qui dit "Restart the test" est en fait pour le débogage du test, pas pour l'exécuter. C'est flou! Je suggère également de mettre une image pour l'étape: "Inspect the align2 object, right-click on its shapes variable and select halt on write'. Parce que cette étape a différentes icônes non vues dans le tutoriel.

![image](https://user-images.githubusercontent.com/6172732/122955164-eef66600-d34d-11eb-816b-9ee6cf106647.png)

**Comment by StevenCostiou** [comment]
Tout est expliqué dans le tutorial en fait, avec des screenshots donc pas besoin de remettre ici.
